In [1]:
import numpy as np
from matplotlib import pyplot as plt

In [48]:
def gauss_method(A, b):
    n = A.shape[0]
    for i in range(0, n - 1):
        for j in range(i + 1, n):
            c = A[j][i]
            A[j] -= A[i] * c / A[i][i]
            b[j] -= b[i] * c / A[i][i]
    x = np.zeros(n)
    for i in range(n - 1, -1, -1): # первое -1 это типа предначальный элепмент, второе вычитаем типа идем в обратном порядке
        s = 0
        for j in range(i + 1, n):
            s += A[i][j] * x[j]
        x[i] = (b[i] - s) / A[i][i]
    return x

In [49]:
A = np.array([[1, 2, 0], [3, 4, 5], [0, 6, 7]], dtype = float)
b = np.array([5, 6, 5], dtype = float)

In [50]:
x = gauss_method(A, b)
print(x)

[ 1.  2. -1.]


In [90]:
def check_zeros(A):
    n = A.shape[0]
    for i in range(0, n):
        if A[i][i] == 0:
            for j in range(0, n):
                if A[j][i] != 0 and A[i][j] != 0:
                    print(A[i], A[j])
                    t = A[i].copy()
                    A[i] = A[j].copy()
                    A[j] = t.copy()
                    #print(A[i], A[j])
                    break
    return A

In [91]:
C = np.array([[0, 2, 1], [3, 4, 5], [0, 6, 0]], dtype = float)
print(check_zeros(C))

[0. 2. 1.] [3. 4. 5.]
[0. 6. 0.] [0. 2. 1.]
[[3. 4. 5.]
 [0. 6. 0.]
 [0. 2. 1.]]
